name: prueba5
description: A new Flutter project

publish_to: "none" # Remove if publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    

  url_launcher: ^6.2.5
  external_app_launcher: ^4.0.3
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/imagen/fondo.png

  # Descomenta esta sección si tienes imágenes o archivos que quieres usar
  # assets:
  #   - assets/

  # Descomenta esta sección si usas fuentes personalizadas
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFontFile.ttf
